title:  Randomblog
tagline:  shower thoughts

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'https-lenpaul-github-io-lagrange'
menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/aarengee'}
- {icon: 'twitter', link: 'https://twitter.com/aarengee'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/rijul-gupta-2a7293104'}
- {icon: 'steam', link: 'http://steamcommunity.com/id/rijul'}
- {icon: 'paper-plane', link: 'https://t.me/aarengee'}
- {icon: 'rss-square', link: 'feed.xml'}
